export default {
  NAV_DASHBOARD: 'NAV_DASHBOARD',
  NAV_CARD_PROGRAM: 'NAV_CARD_PROGRAM',
  NAV_RESELLER: 'NAV_RESELLER',
  NAV_FLOAT_BALANCE: 'NAV_FLOAT_BALANCE',
  NAV_KYC_MODULE: 'NAV_DASHBOARD', // change !!!

  CARD_PROGRAM_EDIT: 'CARD_PROGRAM_EDIT',
  CARD_PROGRAM_VIEW: 'CARD_PROGRAM_VIEW',
  CARD_PROGRAM_LISTING: 'CARD_PROGRAM_LISTING',

  RESELLER_SUBSCRIPTION_CREATE: 'RESELLER_SUBSCRIPTION_CREATE',
  RESELLER_SUBSCRIPTION_LISTING: 'RESELLER_SUBSCRIPTION_LISTING',
  RESELLER_SUBSCRIPTION_VIEW: 'RESELLER_SUBSCRIPTION_VIEW',
  RESELLER_SUBSCRIPTION_EDIT: 'RESELLER_SUBSCRIPTION_EDIT',
  RESELLER_INVOICE_VIEW: 'RESELLER_INVOICE_VIEW',

  // Float
  FLOAT_ACCOUNT_LISTING: 'FLOAT_ACCOUNT_LISTING',
  FLOAT_ACCOUNT_VIEW: 'FLOAT_ACCOUNT_VIEW',
  STATEMENT_VIEW: 'STATEMENT_VIEW',
  FLOAT_ACCOUNT_SEARCH: 'FLOAT_ACCOUNT_SEARCH',
  STATEMENT_DOWNLOAD: 'STATEMENT_DOWNLOAD',
  DEBIT_CREDIT_INSTRUCT_VIEW: 'DEBIT_CREDIT_INSTRUCT_VIEW',
  DEBIT_CREDIT_INSTRUCT_EDIT: 'DEBIT_CREDIT_INSTRUCT_EDIT',
  DEBIT_CREDIT_INSTRUCT_APPROVE: 'DEBIT_CREDIT_INSTRUCT_APPROVE',
  UNALLOCATED_FLOAT_VIEW: 'UNALLOCATED_FLOAT_VIEW',

  // Kyc
  KYC_DASHBOARD_ALL_INVOICES: 'KYC_DASHBOARD_ALL_INVOICES',
  KYC_DASHBOARD_WORKFLOW: 'KYC_DASHBOARD_WORKFLOW',
  KYC_DASHBOARD_E_MONEY: 'KYC_DASHBOARD_E_MONEY',
  KYC_DASHBOARD_SEARCH: 'KYC_DASHBOARD_SEARCH',

  KYC_WORKFLOW_MAIN_PAGE: 'KYC_WORKFLOW_MAIN_PAGE',
  KYC_WORKFLOW: 'KYC_WORKFLOW',

  KYC_SEARCH_FILTER: 'KYC_SEARCH_FILTER',
  KYC_SEARCH_ACTION: 'KYC_SEARCH_ACTION',
  KYC_SEARCH_VIEW: 'KYC_SEARCH_VIEW',

  KYC_PRODUCT_CONFIG_CREATE_CLIENT: 'KYC_PRODUCT_CONFIG_CREATE_CLIENT',

  KYC_MAIN_PAGE_BACK_SEARCH: 'KYC_MAIN_PAGE_BACK_SEARCH',
  KYC_MAIN_PAGE_BACK_WORKFLOW: 'KYC_MAIN_PAGE_BACK_WORKFLOW',
  KYC_MAIN_PAGE_TERMINATE_APP: 'KYC_MAIN_PAGE_TERMINATE_APP',
  KYC_MAIN_PAGE_RESEND_SMS: 'KYC_MAIN_PAGE_RESEND_SMS',
  KYC_MAIN_PAGE_ID_VIEW: 'KYC_MAIN_PAGE_ID_VIEW',
  KYC_MAIN_PAGE_ID_ACTION: 'KYC_MAIN_PAGE_ID_ACTION',
  KYC_MAIN_PAGE_POA_VIEW: 'KYC_MAIN_PAGE_POA_VIEW',
  KYC_MAIN_PAGE_POA_ACTION: 'KYC_MAIN_PAGE_POA_ACTION',
  KYC_MAIN_PAGE_SANCTION_VIEW: 'KYC_MAIN_PAGE_SANCTION_VIEW',
  KYC_MAIN_PAGE_SANCTION_ACTION: 'KYC_MAIN_PAGE_SANCTION_ACTION',

  KYC_ID_VIEW: 'KYC_ID_VIEW',
  KYC_ID_ACTION: 'KYC_ID_ACTION',
  KYC_ID_ACTION_SAVE: 'KYC_ID_ACTION_SAVE',
  KYC_ID_ACTION_BROWSE: 'KYC_ID_ACTION_BROWSE',
  KYC_ID_ACTION_CLOSE: 'KYC_ID_ACTION_CLOSE',

  KYC_POA_VIEW: 'KYC_POA_VIEW',
  KYC_POA_ACTION: 'KYC_POA_ACTION',
  KYC_POA_ACTION_BROWSE: 'KYC_POA_ACTION_BROWSE',
  KYC_POA_ACTION_SAVE: 'KYC_POA_ACTION_SAVE',
  KYC_POA_ACTION_CLOSE: 'KYC_POA_ACTION_CLOSE',

  KYC_SANCTION_VIEW: 'KYC_SANCTION_VIEW',
  KYC_SANCTION_ACTION: 'KYC_SANCTION_ACTION',
  KYC_SANCTION_ACTION_SAVE: 'KYC_SANCTION_ACTION_SAVE',
  KYC_SANCTION_ACTION_BROWSE: 'KYC_SANCTION_ACTION_BROWSE',
  KYC_SANCTION_ACTION_CLOSE: 'KYC_SANCTION_ACTION_CLOSE',

  ALL_PERMISSION: 'ALL_PERMISSION'
}
