import ROLES from './roles'
import PERMISSIONS from './permission'

const rolesPermissions = {
  [ROLES.TECHNICAL_ADMIN]: [
    // Card Program
    PERMISSIONS.CARD_PROGRAM_EDIT,
    PERMISSIONS.CARD_PROGRAM_VIEW,
    PERMISSIONS.CARD_PROGRAM_LISTING,
    // Reseller
    PERMISSIONS.RESELLER_SUBSCRIPTION_LISTING,
    PERMISSIONS.RESELLER_SUBSCRIPTION_CREATE,
    PERMISSIONS.RESELLER_SUBSCRIPTION_EDIT,
    PERMISSIONS.RESELLER_SUBSCRIPTION_VIEW,
    PERMISSIONS.RESELLER_INVOICE_VIEW,
    // Float Account
    PERMISSIONS.FLOAT_ACCOUNT_SEARCH,
    PERMISSIONS.FLOAT_ACCOUNT_LISTING,
    PERMISSIONS.UNALLOCATED_FLOAT_VIEW,
    PERMISSIONS.STATEMENT_VIEW,
    PERMISSIONS.DEBIT_CREDIT_INSTRUCT_EDIT,
    PERMISSIONS.DEBIT_CREDIT_INSTRUCT_APPROVE,
    // Kyc Module

  ],
  [ROLES.FINANCE_MANAGER]: [
    // Card Program
    PERMISSIONS.CARD_PROGRAM_VIEW,
    PERMISSIONS.CARD_PROGRAM_LISTING,
    // Reseller
    PERMISSIONS.RESELLER_SUBSCRIPTION_LISTING,
    PERMISSIONS.RESELLER_SUBSCRIPTION_VIEW,
    PERMISSIONS.RESELLER_INVOICE_VIEW,
    // Float Account
    PERMISSIONS.FLOAT_ACCOUNT_SEARCH,
    PERMISSIONS.FLOAT_ACCOUNT_LISTING,
    PERMISSIONS.UNALLOCATED_FLOAT_VIEW,
    PERMISSIONS.STATEMENT_VIEW,
    PERMISSIONS.DEBIT_CREDIT_INSTRUCT_EDIT,
    // Kyc Module
    PERMISSIONS.KYC_DASHBOARD_ALL_INVOICES,
  ],
  [ROLES.FINANCE_OPERATION]: [
    // Card Program
    PERMISSIONS.CARD_PROGRAM_VIEW,
    PERMISSIONS.CARD_PROGRAM_LISTING,
    // Reseller
    PERMISSIONS.RESELLER_SUBSCRIPTION_LISTING,
    PERMISSIONS.RESELLER_SUBSCRIPTION_VIEW,
    PERMISSIONS.RESELLER_INVOICE_VIEW,
    // Float Account
    PERMISSIONS.FLOAT_ACCOUNT_SEARCH,
    PERMISSIONS.FLOAT_ACCOUNT_LISTING,
    PERMISSIONS.UNALLOCATED_FLOAT_VIEW,
    PERMISSIONS.STATEMENT_VIEW,
    // Kyc Module
    PERMISSIONS.KYC_DASHBOARD_ALL_INVOICES,
  ],
  [ROLES.BUSINESS_OPERATION]: [
    // Card Program
    PERMISSIONS.CARD_PROGRAM_VIEW,
    PERMISSIONS.CARD_PROGRAM_LISTING,
    // Reseller
    PERMISSIONS.RESELLER_SUBSCRIPTION_LISTING,
    PERMISSIONS.RESELLER_SUBSCRIPTION_CREATE,
    PERMISSIONS.RESELLER_SUBSCRIPTION_EDIT,
    PERMISSIONS.RESELLER_SUBSCRIPTION_VIEW,
    PERMISSIONS.RESELLER_INVOICE_VIEW,
    // Float Account
    PERMISSIONS.FLOAT_ACCOUNT_SEARCH,
    PERMISSIONS.FLOAT_ACCOUNT_LISTING,
    PERMISSIONS.UNALLOCATED_FLOAT_VIEW,
    PERMISSIONS.STATEMENT_VIEW,
    // Kyc Module

  ],
}

export default rolesPermissions
